control:
  hosts: 
    control.stuffserver.net:

ipaserver:
  hosts:
    ipaserver.home.stuffserver.net:
  vars:
    ipaadmin_password: admpassword
    ipadm_password: dmpassword
    ipaserver_domain: home.stuffserver.net
    ipaserver_realm: HOME
    ipaserver_forwarders:
      - 1.1.1.1
      - 1.0.0.1

nodes:
  hosts:
    pve-[1:3].stuffserver.net:
